<?php
return array(
    "area" => array(
        "NUS" => 1,
        "R10" => 2,
        "R1X" => 3,
        "R1Y" => 4,
        "R1Z" => 5,
        "R20" => 6,
        "R30" => 7,
        "R40" => 8,
        "R4N5" => 9,
        "R50" => 10,
        "YCUOK" => 11,
    ),
    "product" => array(
        "EP00" => 1,
        "EPC0" => 2, // Crude Oil
        "EPD0" => 3, // Distillate Fuel Oil
        "EPD00H" => 4,
        "EPDM10" => 5,
        "EPDXL0"    => 6,
        "EPJK"  => 7,
        "EPL0XP" => 8,
        "EPLLPYN"   => 9,
        "EPPLLPZ" => 10,
        "EPM0" => 11, // Total gasoline
        "EPM0C" => 12, 
        "EPM0CA" => 13,
        "EPM0CAG55" => 14,
        "EPM0CO" => 15,
        "EPM0F" => 16,
        "EPM0R" => 17,
        "EPM0RA" => 18,
        "EPOBG" => 19,
        "EPOBGCC" => 20,
        "EPOBGCG" => 21,
        "EPOGBCO" => 22,
        "EPOBGRG" => 23,
        "EPOBGRR" => 24,
        "EPOBGRRA" => 25,
        "EPOBGRRE" => 26,
        "EPOOXE" => 27,
        "EPPA" => 28,
        "EPPK" => 29,
        "EPPO6" => 30,
        "EPPR" => 31,
        "EPPU" => 32,
    ),
    "process" => array(
        "SAE" => 1,
        "SAS" => 2,
        "SAX" => 3,
        "SAXL" => 4,
        "SAXP" => 5,
        "SKA" => 6,
        "SKB" => 7,
    ),
    "units" => array(
        "MBBL" => 1,
    ),
);
